services:
  mysql-shopping:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-shopping:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql-shopping: