spring:
  application:
    name: shopping-backend

  flyway:
    enabled: true
    validate-on-migrate: true
    locations:
      - classpath:db/migration/ddl
      - classpath:db/migration/dml
      - classpath:db/migration/seed/dev
    create-schemas: true
    baseline-version: 1

  datasource:
    url: jdbc:mysql://localhost:3306/shopping?&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect