spring:
  application:
    name: shopping-backend

  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
    create-schemas: true
    baseline-version: 1

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



#url: jdbc:mysql://3.85.234.184:3306/shopping?&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
