name: Deploy app shopping-backend

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build project
        run: mvn clean install
      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t guilhermerbs/shopping-backend .
      - name: Push image docker
        run: docker push guilhermerbs/shopping-backend

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image From Docker Hub
        run: docker pull guilhermerbs/shopping-backend:latest
      - name: Remove docker container
        run: docker rm -f deploy_shopping_backend || true
      - name: Run Docker container
        run: docker run -d -p 8080:8080 -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} -e DATABASE_URL=${{ secrets.DATABASE_URL }} --name deploy_shopping_backend guilhermerbs/shopping-backend